#! /bin/sh

cd "`dirname \"$0\"`" &&
MAILCAPS="`pwd`"/.mailcap &&
export MAILCAPS &&

rm -rf tmp &&
mkdir tmp || exit 1

RC=0

test1() {
   ../mimedecode.py -H test -f utf-8 input/"$1" >tmp/"$1" || return 1
   if cmp -s expected/"$1" tmp/"$1"; then
      rm tmp/"$1" && return 0 || return 1
   else
      diff --text expected/"$1" tmp/"$1" >tmp/"$1".diff
      return 1
   fi
}

for f in input/*.txt; do
   n="`basename \"$f\"`"
   echo -n "$n "
   if test1 "$n"; then
      echo "ok"
   else
      echo "fail"
      RC=1
   fi
done

if [ "$RC" -eq 0 ]; then
   echo "All tests passed!"
   rmdir tmp
fi

exit $RC
