DOCBOOK_XSL=/usr/share/xml/docbook/stylesheet/docbook-xsl

mimedecode.html: mimedecode.docbook Makefile.4xslt
	4xslt $< $(DOCBOOK_XSL)/html/docbook.xsl >$@

mimedecode.man: mimedecode.docbook Makefile.4xslt
	4xslt $< $(DOCBOOK_XSL)/manpages/docbook.xsl
	mv mimedecode.1 $@

mimedecode.txt: mimedecode.html Makefile.4xslt
	elinks -dump -no-numbering -no-references $< >$@
