DOCBOOK_XSL=/usr/share/xml/docbook/stylesheet/docbook-xsl

mimedecode.html: mimedecode.docbook Makefile.xsltproc
	xsltproc $(DOCBOOK_XSL)/html/docbook.xsl $< >$@

mimedecode.txt: mimedecode.html Makefile.xsltproc
	elinks -dump $< >$@

mimedecode.man: mimedecode.docbook Makefile.xsltproc
	xsltproc $(DOCBOOK_XSL)/manpages/docbook.xsl $<
	mv mimedecode.py.1 $@
