mimedecode.html: mimedecode.docbook Makefile.sgmlt
	sgmltools -b html $<
	mv mimedecode/mimedecode.py.html mimedecode.html
	rmdir mimedecode

mimedecode.man: mimedecode.docbook Makefile.sgmlt
	docbook-to-man $< >$@

mimedecode.txt: mimedecode.docbook Makefile.sgmlt
	sgmltools -b txt $<
