#! /bin/sh

"$HOME"/admin/prog/git-scripts/update || exit 1

current="`git config --get --path remote.current.url`"

# Copy mimedecode.docbook with timestamp to avoid rebuilding
exec rsync -ahP "$current"/mimedecode.docbook "$current"/mimedecode.man \
                "$current"/mimedecode.html "$current"/mimedecode.txt .
